# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 300699c60253bb57474707ff3e409464406c8c53935041dab45c5bbaa1592a4f64e478492cd2b6c6936a1afa39f15632d38f378c06a5a70bea454f9195f7f3b0

test:
  secret_key_base: 52fd07fe2ee2cf5963cabd74a6751459244b1b82f8413f2d9d22bf0a07d19729204ae1a91d8f9a685fc23c20710f88e0c4f4b7ad6e18df172e664b70517314d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
